[package]
name = "progspacerust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mlua = { version = "0.8", features = ["lua54", "vendored"] }
opencv = "0.68.0"
lazy_static = "1.4.0"
regex = "1"